name: Release
on:
  push:
    tags:
      - 'version-*'

jobs:
  release:
    runs-on: ubuntu-latest
    name:    release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make
        run:  make
      - name: install_aws
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update --bin-dir /usr/local/bin
          rm -rf ./aws ./awscliv2.zip
      - name: push
        env:
          BUILDER: ${{ secrets.BUILDER }}
          BUILDERCRED: ${{ secrets.BUILDERCRED }}
        run: make push
